### PR TITLE
Use new blog domain

### PR DESCRIPTION
**Pull request by MGPalmer**
I'm not sure how to test this locally, sorry!

Please also see the note about the https redirect in the ticket: https://github.com/nushell/blog/issues/19

### CODE REVIEW

**Comment by sebastian-xyz** [comment]
Looks good. I'm not sure either how to test the feed locally. Let's merge and see if it fixes the link :)

**Comment by sebastian-xyz** [comment]
It looks like jekyll adds `/blog/feed.xml` to the url given in `_config.yml` because now we get `/blog/blog/feed.xml`.

**Comment by sebastian-xyz** [comment]
I updated `_config.yml` to fix it. Hope that's okay for you :)

Thank you!

**Comment by MGPalmer** [comment]
Nice, seems to work for me!

**Pull request merged**
