### PR TITLE
first attempt to create the blog

### PR DESCRIPTION
**Pull request by sebastian-xyz**
I took the posts and pictures from your blog @jonathandturner  hope that's okay :)

### CODE REVIEW

**Comment by jonathandturner** [comment]
Awesome!

**Comment by jonathandturner** [comment]
We might decide to change the pictures later :)

**Comment by jonathandturner** [comment]
It's now live at: https://www.nushell.sh/blog/

**Comment by sebastian-xyz** [comment]
You might want to add an ID for Google analytics to both sites

**Comment by jonathandturner** [comment]
@sebastian-xyz - good point! would you mind filing an issue for it on the repos to remind us to do that?

**Pull request merged**
